# Configuration for stop line filter

# ======= STOPPING PARAMETERS =======
should_stop_dist: 0.2  # Distance (in m) from stop line where `should_stop` flag is set (≥ 0.18)  
stop_distance: -0.08  # Distance (in m) from the stopping point relative to the bot's center (negative = stops before the line)  

# ======= DETECTION PARAMETERS =======
min_segs: 6  # Minimum number of red segments required to confirm a stop line  
min_y: -0.08  # Minimum y-coordinate (in m; relative to bot) for a red line to be considered a stop line (prevents wrong side detections)  
off_time: 2  # Time delay (in s) before detecting stop lines again after clearing an intersection 
