#lane_control/lane_controller_node
v_bar: 0.25
k_d: -4.5       # should be <= 0
k_theta: -6.25   # should be <= 0
k_Id: -0.5      # should be <= 0
k_Iphi: 0.0    # should be <= 0
theta_thres_max: 1.0
theta_thres_min: -0.8
d_thres: 0.2615
d_offset: 0.0
deriv_type: "value"
use_LEDs: true

omega_ff: 0.15

integral_bounds:
  d:
    top: 0.3
    bot: -0.3
  phi:
    top: 1.2
    bot: -1.2

d_resolution: 0.011
phi_resolution: 0.051

stop_line_slowdown:
  start: 0.6
  end: 0.15

verbose: 0


# Turns parameter
l_turn_v: 0.3
l_turn_omega: 2
l_turn_secs: 1.2

r_turn_v: 0.3
r_turn_omega: -4.75
r_turn_secs: 0.8

s_turn_v: 0.22
s_turn_omega: 0.0
s_turn_secs: 4
